### ISSUE TITLE
invalid metric type "GAUGE" error for MSSQL exporter

### ISSUE THREAD

**Issue by mdharpur** [DanielOliver/mssql_exporter#1]
Hi, While using the exporter I'm getting an error in Prometheus. **invalid metric type "GAUGE"**. I think all the metric type should be in lowercase.

**Comment by DanielOliver** [comment]
Good day!  You're right.  It looks like the latest version of prometheus .net library does this:  
https://github.com/prometheus-net/prometheus-net/blob/2a874f0f7877fbcd17e41c638d724159f6bfdf5d/Prometheus.NetStandard/Collector.cs#L122

This exporter needs to be updated.  I just haven't quite gotten around to updating this project's dependencies yet.  (or updating the version of prometheus I'm personally using)

**Comment by mdharpur** [comment]
Thanks for your reply Oliver. Could you please tell me what version of Prometheus it works with?

**Comment by DanielOliver** [comment]
The previous version of [this exporter 0.2.1](https://github.com/DanielOliver/mssql_exporter/releases/tag/0.2.1) was working with prometheus-2.3.2.  

I just released a new version of [this exporter 0.3.0](https://github.com/DanielOliver/mssql_exporter/releases/tag/0.3.0) is working with prometheus-2.8.0. I haven't done extensive testing but it does lower-case the counter types which Prometheus changed recently it seems.

**Comment by mdharpur** [comment]
Thanks Oliver......!!! This is now working with the latest version of Prometheus.

**Comment by DanielOliver** [comment]
Awesome and thank you!  I appreciate the head up!  I'll be taking this opportunity to update my own instances running.
