### ISSUE TITLE
Connection failing

### ISSUE THREAD

**Issue by patrickschilder** [DanielOliver/mssql_exporter#5]
Hi,

I have the exporter running on the windows database server. When i do a curl command i get the following response: 
`# HELP mssql_exceptions Number of queries throwing exceptions.
# TYPE mssql_exceptions gauge
mssql_exceptions 4
# HELP mssql_deadlocks mssql_deadlocks
# TYPE mssql_deadlocks gauge
mssql_deadlocks 0
# HELP mssql_up mssql_up
# TYPE mssql_up gauge
mssql_up 0
# HELP mssql_timeouts Number of queries timing out.
# TYPE mssql_timeouts gauge
mssql_timeouts 0
# HELP mssql_process_status Counts the number of processes per status
# TYPE mssql_process_status gauge`

I used the proposed command to start the exporter: 
mssql_exporter.exe serve -ConfigFile "test.json" -DataSource "Server=tcp:{ YOUR DATABASE HERE },1433;Initial Catalog={ YOUR INITIAL CATALOG HERE };Persist Security Info=False;User ID={ USER ID HERE };Password={ PASSWORD HERE };MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

It reports the database is down, while it is actually up. How can i debug/analyse why the connection to the DB is failing?

Kind regards,
Patrick

**Comment by patrickschilder** [comment]
After analyzing the logs on the MS SQL server i found the following entries:

A fatal alert was generated and sent to the remote endpoint. This may result in termination of the connection. The TLS protocol defined fatal error code is 48. The Windows SChannel error state is 552

The certificate received from the remote server was issued by an untrusted certificate authority. Because of this<c/> none of the data contained in the certificate can be validated. The SSL connection request has failed. The attached data contains the server certificate.

**Comment by Mario-Hofstaetter** [comment]
@djpasch In your connection string it says `Encrypt=True`
Do you need Encryption? Did you try turning it off?

I'm not proficient in using certificates, so can't give advice on that MS SQL message.

**Comment by patrickschilder** [comment]
Hi Mario,

Within our company all traffic needs to be encrypted, also internal traffic. Disabling it is not an option unfortunately.

Hope someone can help me out.

Kind regards,
Patrick

**Comment by Mario-Hofstaetter** [comment]
The error you posted mentions an certificate is untrusted. Did you ask your IT about this? It may be a self signed cert that has not been added as an exception.

**Comment by patrickschilder** [comment]
I need to check that, for now let’s close this issue
